### ISSUE TITLE
docker compose issue

### ISSUE THREAD

**Issue by anoureldin** [davidmonterocrespo24/OdooMicroSaas#32]
hello how are you ?

can you check this error 
i get it on odoo 16 and use last version 

#12/06/2023, 19:20:55 [INFO] Docker Compose command executed successfully

#12/06/2023, 19:20:55 Error to execute command: Command 'docker-compose -f /opt/odoo/odoo_docker/data/odoo_15_from_template/docker-compose.yml up -d' returned non-zero exit status 1.

#12/06/2023, 19:20:55 [INFO] Path to modified docker-compose.yml file

#12/06/2023, 19:20:55 [INFO] Archivo odoo.conf creado exitosamente en /opt/odoo/odoo_docker/data/odoo_15_from_template/etc/odoo.conf

#12/06/2023, 19:20:55 [INFO] Starting Odoo Instance False

**Comment by anoureldin** [comment]
Docker Compose version v2.17.3

**Comment by aitmlouk** [comment]
Same error here!! 
(MacOs, Docker Compose version v2.23.0-desktop.1)

**Comment by davidmonterocrespo24** [comment]
Hello, 
This bug has been corrected in the new version

**Comment by anoureldin** [comment]
thanks i will test

**Comment by davidmonterocrespo24** [comment]
This bug has been fixed
