### ISSUE TITLE
Create Instance from Template is Error 

### ISSUE THREAD

**Issue by jaronemo** [davidmonterocrespo24/OdooMicroSaas#33]
Impacted versions:
16.0
Steps to reproduce:
When I create an instance from the Odoo15 Template, the first one I create is named Odoo15-Dev. After that, I create odoo15-demo, only to discover that all the Variables values in the odoo15-demo instance are missing. Then, if I try to start the odoo15-demo instance, it will result in an error!

Video/Screenshot link (optional):
![image](https://github.com/davidmonterocrespo24/odoo_micro_saas/assets/8476734/1466c9da-d2fa-40e5-85a6-b024ca3ae44c)
![image](https://github.com/davidmonterocrespo24/odoo_micro_saas/assets/8476734/af78e110-901b-4963-bc52-82157d0ed34c)
![image](https://github.com/davidmonterocrespo24/odoo_micro_saas/assets/8476734/501e0276-22c8-46ff-9c4d-f4430e86d5d9)

**Comment by davidmonterocrespo24** [comment]
This bug has been fixed
