### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by khahmed94** [davidmonterocrespo24/OdooMicroSaas#35]
hello,
i have this error can u check it?
i'm using on odoo sh 17

#09/08/2024, 01:58:55 [ERROR] /bin/sh: 1: docker-compose: not found

#09/08/2024, 01:58:55 [INFO] **** Execute the following command manually from the terminal for more details **** docker-compose -f /home/odoo/odoo_docker/data/cc/docker-compose.yml up -d

#09/08/2024, 01:58:55 Error to execute command: Command 'docker-compose -f /home/odoo/odoo_docker/data/cc/docker-compose.yml up -d' returned non-zero exit status 127.

#09/08/2024, 01:58:55 [INFO] Path to modified docker-compose.yml file

#09/08/2024, 01:58:55 [INFO] Archivo odoo.conf creado exitosamente en /home/odoo/odoo_docker/data/cc/etc/odoo.conf

#09/08/2024, 01:58:55 [INFO] Starting Odoo Instance False

**Comment by davidmonterocrespo24** [comment]
> hello, i have this error can u check it? i'm using on odoo sh 17
> 
> #9/08/2024, 01:58:55 [ERROR] /bin/sh: 1: docker-compose: not found
> 
> #9/08/2024, 01:58:55 [INFO] **** Execute the following command manually from the terminal for more details **** docker-compose -f /home/odoo/odoo_docker/data/cc/docker-compose.yml up -d
> 
> #9/08/2024, 01:58:55 Error to execute command: Command 'docker-compose -f /home/odoo/odoo_docker/data/cc/docker-compose.yml up -d' returned non-zero exit status 127.
> 
> #9/08/2024, 01:58:55 [INFO] Path to modified docker-compose.yml file
> 
> #9/08/2024, 01:58:55 [INFO] Archivo odoo.conf creado exitosamente en /home/odoo/odoo_docker/data/cc/etc/odoo.conf
> 
> #9/08/2024, 01:58:55 [INFO] Starting Odoo Instance False

Hi,
odoo.sh does not support creating docker containers
